const fs = require('fs');
const path = require('path');
const XLSX = require(path.join(__dirname, '../node_modules/xlsx'));

const root = path.join(__dirname, '..');
const wb = XLSX.readFile(path.join(root, 'product_with_descriptions.xlsx'));
const descMap = {};
XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval: '' }).forEach(r => {
  const id = String(r.model || '').trim();
  const desc = String(r.description || '').trim();
  if (id && desc) descMap[id] = desc;
});

let raw = fs.readFileSync(path.join(root, 'products.json'), 'utf8');
if (raw.charCodeAt(0) === 0xFEFF) raw = raw.slice(1);
const products = JSON.parse(raw);

const extras = {
  '150935': {
    embed: 'https://drive.google.com/file/d/1oY_5QbtHjPyoEwm99Ljs9Q3ZgJXSZBU2/preview',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність</td><td>3500 ВА / 3500 Вт</td></tr><tr><td>Режим АКБ</td><td>3500 ВА / 3000 Вт</td></tr><tr><td>Пікова потужність</td><td>7000 Вт</td></tr><tr><td>Форма хвилі</td><td>Чиста синусоїда</td></tr><tr><td>ККД інвертора</td><td>93%</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Напруга</td><td>24 В DC</td></tr><tr><td>Напруга заряду</td><td>27.4 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. напруга ХХ</td><td>450 В DC</td></tr><tr><td>Діапазон MPPT</td><td>60–360 В DC</td></tr><tr><td>Макс. потужність PV</td><td>3500 Вт</td></tr><tr><td>Макс. вхідний струм PV</td><td>18 А</td></tr></tbody></table>'
  },
  '142723': {
    description: 'Гібридний інвертор MUST PV18-3224 VPM II - 3200 ВА, 24 В, MPPT 60A.',
    link: 'https://drive.google.com/drive/folders/1Ds5LLBVBJrWKSMc8MOgjYTWmcU6jA0Iy',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність</td><td>3200 ВА / 3200 Вт</td></tr><tr><td>Пікова потужність</td><td>6400 ВА</td></tr><tr><td>Форма сигналу</td><td>Чиста синусоїда</td></tr><tr><td>Регулювання напруги AC (режим АКБ)</td><td>230 В</td></tr><tr><td>ККД інвертора (піковий)</td><td>90–93%</td></tr><tr><td>Час перемикання</td><td>10 мс (UPS / VDE4105) / 20 мс (APL)</td></tr><tr><td colspan="2" class="specs-section"><strong>ВИХІД AC</strong></td></tr><tr><td>Напруга</td><td>230 В AC</td></tr><tr><td>Діапазон вхідної напруги</td><td>170–280 В (UPS) / 90–280 В (APL) / 184–253 В (VDE)</td></tr><tr><td>Діапазон частот</td><td>50 / 60 Гц (автовизначення)</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Номінальна напруга</td><td>24 В DC</td></tr><tr><td>Напруга підтримуючого заряду</td><td>27.4 В DC</td></tr><tr><td>Захист від перезаряду</td><td>30 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ ТА МЕРЕЖЕВИЙ ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. напруга ХХ PV-масиву</td><td>160 В DC</td></tr><tr><td>Діапазон напруги MPPT</td><td>30–128 В DC</td></tr><tr><td>Макс. потужність PV-масиву</td><td>1600 Вт</td></tr><tr><td>Макс. струм сонячного заряду</td><td>60 А</td></tr><tr><td>Макс. ККД</td><td>98%</td></tr><tr><td>Макс. струм заряду від AC</td><td>60 А</td></tr><tr><td>Макс. сумарний струм заряду</td><td>120 А</td></tr><tr><td>Споживання в режимі очікування</td><td>2 Вт</td></tr><tr><td colspan="2" class="specs-section"><strong>МЕХАНІЧНІ ХАРАКТЕРИСТИКИ</strong></td></tr><tr><td>Габарити пристрою (Ш×В×Г)</td><td>254.5 × 367.4 × 103 мм</td></tr><tr><td>Габарити пакування (Ш×В×Г)</td><td>436 × 331 × 189 мм</td></tr><tr><td>Вага нетто / брутто</td><td>5.5 кг / 6.5 кг</td></tr><tr><td colspan="2" class="specs-section"><strong>ІНШЕ</strong></td></tr><tr><td>Вологість</td><td>5–95% (без конденсації)</td></tr><tr><td>Робоча температура</td><td>0°C – 50°C</td></tr><tr><td>Температура зберігання</td><td>-15°C – 60°C</td></tr><tr><td>Гарантія</td><td>2 роки</td></tr><tr><td>Сертифікація</td><td>CE-EMC+LVD (EN6100-6-3, EN6100-6-1, EN IEC62109-1, EN IEC62109-2)</td></tr></tbody></table>'
  },
  '150825': {
    description: 'Гібридний інвертор MUST PV18-1012VPK - 1000 Вт, 12 В, PWM-контролер заряду 50A.',
    link: 'assets/docs/must-pv1800-vpk.pdf',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність</td><td>1000 Вт</td></tr><tr><td>Пікова потужність</td><td>2000 Вт</td></tr><tr><td>Форма сигналу</td><td>Чиста синусоїда</td></tr><tr><td>Регулювання напруги AC (режим АКБ)</td><td>220–240 В ±5%</td></tr><tr><td>ККД інвертора (максимальний)</td><td>93%</td></tr><tr><td>Час перемикання</td><td>10 мс (UPS / VDE4105) / 20 мс (APL)</td></tr><tr><td colspan="2" class="specs-section"><strong>ВХІД AC</strong></td></tr><tr><td>Напруга</td><td>230 В AC</td></tr><tr><td>Діапазон вхідної напруги</td><td>170–280 В (UPS) / 90–280 В / 184–253 В (VDE4105)</td></tr><tr><td>Діапазон частот</td><td>50 / 60 Гц (автовизначення)</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Номінальна напруга</td><td>12 В DC</td></tr><tr><td>Напруга плаваючого заряду</td><td>13.7 В DC</td></tr><tr><td>Захист від перезаряду</td><td>15.5 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ КОНТРОЛЕР ТА AC-ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. напруга ХХ PV-масиву</td><td>55 В DC</td></tr><tr><td>Споживання в режимі очікування</td><td>2 Вт</td></tr><tr><td>Макс. струм заряду від сонячних панелей (PWM)</td><td>50 А</td></tr><tr><td>Макс. струм заряду від AC</td><td>10 А або 20 А</td></tr><tr><td>Макс. сумарний струм заряду</td><td>70 А</td></tr><tr><td colspan="2" class="specs-section"><strong>МЕХАНІЧНІ ХАРАКТЕРИСТИКИ</strong></td></tr><tr><td>Габарити пристрою (Ш×В×Г)</td><td>224 × 337 × 98 мм</td></tr><tr><td colspan="2" class="specs-section"><strong>ІНШЕ</strong></td></tr><tr><td>Вологість</td><td>5–95% (без конденсації)</td></tr><tr><td>Робоча температура</td><td>0°C – 50°C</td></tr><tr><td>Температура зберігання</td><td>-15°C – 60°C</td></tr><tr><td>Гарантія</td><td>2 роки</td></tr><tr><td>Сертифікація</td><td>CE-EMC+LVD, UKCA</td></tr></tbody></table>'
  },
  '151418': {
    description: 'MUST PV18-4024PREM — багатофункціональний гібридний інвертор серії PREM потужністю 4 кВт для автономних та резервних систем живлення. Поєднує функції інвертора, MPPT сонячного зарядного контролера та зарядного пристрою АКБ. Може працювати без акумулятора. Максимальна напруга холостого ходу PV-масиву досягає 450 В. Має подвійний вихід для розумного керування навантаженням.',
    link: 'https://drive.google.com/drive/folders/1oius3OliUsRCaNC2UORanDUFz_M8RR2J',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність</td><td>4000 ВА / 4000 Вт</td></tr><tr><td>Режим АКБ (осн. навантаження)</td><td>3500 ВА / 3500 Вт</td></tr><tr><td>Пікова потужність</td><td>7000 Вт</td></tr><tr><td>Форма хвилі</td><td>Чиста синусоїда</td></tr><tr><td>Регулювання напруги AC (режим АКБ)</td><td>230 В ±5%</td></tr><tr><td>ККД інвертора (піковий)</td><td>90–93%</td></tr><tr><td>Час перемикання</td><td>10 мс (UPS / VDE4105) / 20 мс (APL)</td></tr><tr><td colspan="2" class="specs-section"><strong>ВХІД ЗМІННОГО СТРУМУ</strong></td></tr><tr><td>Напруга</td><td>230 В AC ±5%</td></tr><tr><td>Діапазон вхідної напруги</td><td>170–280 В (UPS) / 90–280 В (APL) / 184–253 В (VDE4105)</td></tr><tr><td>Діапазон частот</td><td>50 / 60 Гц (автовизначення)</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Номінальна напруга</td><td>24 В DC</td></tr><tr><td>Напруга буферного заряду</td><td>27.4 В DC</td></tr><tr><td>Захист від перезаряду</td><td>30 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ ТА AC-ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. напруга ХХ PV-масиву</td><td>450 В DC</td></tr><tr><td>Діапазон напруги MPPT</td><td>60–360 В DC</td></tr><tr><td>Макс. потужність PV-масиву</td><td>4000 Вт</td></tr><tr><td>Макс. вхідний струм PV</td><td>18 А</td></tr><tr><td>Макс. струм заряду від PV</td><td>100 А</td></tr><tr><td>Макс. струм заряду від AC</td><td>60 А</td></tr><tr><td>Макс. сумарний струм заряду</td><td>100 А</td></tr><tr><td>Алгоритм заряду</td><td>3-ступеневий (AGM/GEL/свинець) / 4-ступеневий (Li)</td></tr><tr><td colspan="2" class="specs-section"><strong>МЕХАНІЧНІ ХАРАКТЕРИСТИКИ</strong></td></tr><tr><td>Габарити пристрою (Ш×В×Г)</td><td>318 × 454 × 122.5 мм</td></tr><tr><td>Габарити пакування (Ш×В×Г)</td><td>544.5 × 410 × 200 мм</td></tr><tr><td>Вага нетто / брутто</td><td>8.0 кг / 9.5 кг</td></tr><tr><td colspan="2" class="specs-section"><strong>ІНШЕ</strong></td></tr><tr><td>Вологість</td><td>5–95% (без конденсації)</td></tr><tr><td>Робоча температура</td><td>-10°C – 50°C</td></tr><tr><td>Температура зберігання</td><td>-15°C – 60°C</td></tr><tr><td>Інтерфейс зв\'язку</td><td>USB, Wi-Fi, Bluetooth, RS-485/CAN</td></tr><tr><td>Адаптивний комплект</td><td>Так</td></tr><tr><td>Гарантія</td><td>2 роки</td></tr><tr><td>Сертифікація</td><td>CE-EMC+LVD</td></tr></tbody></table>'
  },
  '148317': {
    description: 'MUST PV18-2012 ECO — багатофункціональний гібридний інвертор потужністю 2 кВт для автономних та резервних систем живлення. Поєднує функції інвертора, MPPT сонячного зарядного пристрою та зарядного пристрою для акумуляторів. Може працювати без акумулятора. Має подвійний вихід для керування навантаженням.',
    link: 'https://drive.google.com/drive/folders/1oius3OliUsRCaNC2UORanDUFz_M8RR2J',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність (Осн.+Доп.)</td><td>2000 ВА / 2000 Вт</td></tr><tr><td>Режим АКБ (Осн.+Доп.)</td><td>2000 ВА / 1600 Вт</td></tr><tr><td>Пікова потужність</td><td>3200 Вт</td></tr><tr><td>Форма хвилі</td><td>Чиста синусоїда</td></tr><tr><td>Стабілізація напруги (режим АКБ)</td><td>230 В ±5%</td></tr><tr><td>ККД інвертора (піковий)</td><td>90–93%</td></tr><tr><td>Час перемикання</td><td>10 мс (UPS / VDE4105) / 20 мс (APL)</td></tr><tr><td colspan="2" class="specs-section"><strong>ВХІД ЗМІННОГО СТРУМУ</strong></td></tr><tr><td>Напруга</td><td>230 В AC ±5%</td></tr><tr><td>Діапазон вхідної напруги</td><td>170–280 В (UPS) / 90–280 В (APL) / 184–253 В (VDE4105)</td></tr><tr><td>Діапазон частот</td><td>50 / 60 Гц</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Номінальна напруга</td><td>12 В DC</td></tr><tr><td>Напруга підтримуючого заряду</td><td>13.7 В DC</td></tr><tr><td>Захист від перезаряду</td><td>15 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ ТА AC-ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. вхідна напруга ХХ СП</td><td>400 В DC</td></tr><tr><td>Макс. вхідний струм СП</td><td>16 А</td></tr><tr><td>Макс. потужність масиву СП</td><td>2000 Вт</td></tr><tr><td>Діапазон MPPT напруги</td><td>30–320 В DC</td></tr><tr><td>Макс. струм сонячного заряду</td><td>80 А</td></tr><tr><td>Макс. струм заряду від AC</td><td>80 А</td></tr><tr><td>Макс. загальний струм заряду</td><td>80 А</td></tr><tr><td>Алгоритм заряду</td><td>3-ступеневий (свинець, AGM/GEL) / 4-ступеневий (Li)</td></tr><tr><td colspan="2" class="specs-section"><strong>МЕХАНІЧНІ ХАРАКТЕРИСТИКИ</strong></td></tr><tr><td>Габарити пристрою (Ш×В×Г)</td><td>290 × 367 × 111 мм</td></tr><tr><td>Габарити пакування (Ш×В×Г)</td><td>446 × 394 × 187 мм</td></tr><tr><td>Вага нетто / брутто</td><td>6 кг / 7.2 кг</td></tr><tr><td colspan="2" class="specs-section"><strong>ІНШЕ</strong></td></tr><tr><td>Вологість</td><td>5–95% (без конденсації)</td></tr><tr><td>Робоча температура</td><td>-10°C – 50°C</td></tr><tr><td>Температура зберігання</td><td>-15°C – 60°C</td></tr><tr><td>Інтерфейс зв\'язку</td><td>USB, Wi-Fi, RS-485/CAN</td></tr><tr><td>Захист від пилу (Anti-dust Kit)</td><td>Ні</td></tr><tr><td>Гарантія</td><td>2 роки</td></tr></tbody></table>'
  },
  '150752': {
    description: 'Must PV18-6248 ECO — потужний гібридний інвертор серії ECO потужністю 6.2 кВт для автономних та резервних систем живлення. Поєднує функції інвертора, MPPT сонячного зарядного пристрою та зарядного пристрою для акумуляторів. Може працювати без акумулятора. Максимальна вхідна напруга від сонячних панелей досягає 500 В. Має подвійний вихід для керування навантаженням.',
    link: 'https://drive.google.com/drive/folders/1oius3OliUsRCaNC2UORanDUFz_M8RR2J',
    specs: '<h3 style="margin:20px 0 10px;font-size:1rem;color:var(--color-dark)">Технічні характеристики</h3><table class="specs-table"><tbody><tr><td colspan="2" class="specs-section"><strong>ВИХІД ІНВЕРТОРА</strong></td></tr><tr><td>Номінальна потужність (Осн.+Доп.)</td><td>6200 ВА / 6200 Вт</td></tr><tr><td>Режим АКБ (Осн.+Доп.)</td><td>6200 ВА / 6200 Вт</td></tr><tr><td>Пікова потужність</td><td>12400 Вт</td></tr><tr><td>Форма хвилі</td><td>Чиста синусоїда</td></tr><tr><td>Стабілізація напруги (режим АКБ)</td><td>230 В ±5%</td></tr><tr><td>ККД інвертора (піковий)</td><td>90–93%</td></tr><tr><td>Час перемикання</td><td>10 мс (UPS / VDE4105) / 20 мс (APL)</td></tr><tr><td colspan="2" class="specs-section"><strong>ВХІД ЗМІННОГО СТРУМУ</strong></td></tr><tr><td>Напруга</td><td>230 В AC ±5%</td></tr><tr><td>Діапазон вхідної напруги</td><td>170–280 В (UPS) / 90–280 В (APL) / 184–253 В (VDE4105)</td></tr><tr><td>Діапазон частот</td><td>50 / 60 Гц</td></tr><tr><td colspan="2" class="specs-section"><strong>АКУМУЛЯТОР</strong></td></tr><tr><td>Номінальна напруга</td><td>48 В DC</td></tr><tr><td>Напруга підтримуючого заряду</td><td>54.8 В DC</td></tr><tr><td>Захист від перезаряду</td><td>60 В DC</td></tr><tr><td colspan="2" class="specs-section"><strong>СОНЯЧНИЙ ТА AC-ЗАРЯДНИЙ ПРИСТРІЙ</strong></td></tr><tr><td>Макс. вхідна напруга ХХ СП</td><td>500 В DC</td></tr><tr><td>Макс. вхідний струм СП</td><td>28 А</td></tr><tr><td>Макс. потужність масиву СП</td><td>6200 Вт</td></tr><tr><td>Діапазон MPPT напруги</td><td>120–450 В DC</td></tr><tr><td>Макс. струм сонячного заряду</td><td>120 А</td></tr><tr><td>Макс. струм заряду від AC</td><td>100 А</td></tr><tr><td>Макс. загальний струм заряду</td><td>120 А</td></tr><tr><td>Алгоритм заряду</td><td>3-ступеневий (свинець, AGM/GEL) / 4-ступеневий (Li)</td></tr><tr><td colspan="2" class="specs-section"><strong>МЕХАНІЧНІ ХАРАКТЕРИСТИКИ</strong></td></tr><tr><td>Габарити пристрою (Ш×В×Г)</td><td>318 × 454 × 122.5 мм</td></tr><tr><td>Габарити пакування (Ш×В×Г)</td><td>544.5 × 410 × 200 мм</td></tr><tr><td>Вага нетто / брутто</td><td>10 кг / 11.6 кг</td></tr><tr><td colspan="2" class="specs-section"><strong>ІНШЕ</strong></td></tr><tr><td>Вологість</td><td>5–95% (без конденсації)</td></tr><tr><td>Робоча температура</td><td>-10°C – 50°C</td></tr><tr><td>Температура зберігання</td><td>-15°C – 60°C</td></tr><tr><td>Інтерфейс зв\'язку</td><td>USB, Wi-Fi, RS-485/CAN</td></tr><tr><td>Захист від пилу (Anti-dust Kit)</td><td>Так</td></tr><tr><td>Гарантія</td><td>2 роки</td></tr></tbody></table>'
  }
};

products.forEach(p => {
  p.description = descMap[p.id] || p.description || '';
  p.link  = p.link  || '';
  p.embed = p.embed || '';
  p.specs = p.specs || '';
  if (extras[p.id]) Object.assign(p, extras[p.id]);
});

['142723','150825','150935','151418','148317','150752'].forEach(id => {
  const p = products.find(x => x.id === id);
  console.log(id, '| specs:', !!p?.specs, '| link:', !!p?.link, '| desc:', p?.description?.substring(0, 50));
});

fs.writeFileSync(path.join(root, 'products.json'), JSON.stringify(products, null, 2), 'utf8');
console.log('Done — products:', products.length);
